### ISSUE TITLE
ImportError: No module named dispatch

### ISSUE THREAD

**Issue by micah** [meejah/carml#13]
Using 929abb4d78642e8e666c8322e459c1b3c142eef6, I tried to install on debian sid, and had the following problem:

```
micah@reeds:carml$ make
virtualenv venv
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/micah/working/tor/carml/venv/bin/python2
Also creating executable in /home/micah/working/tor/carml/venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
./venv/bin/pip install -U pip
Requirement already up-to-date: pip in ./venv/lib/python2.7/site-packages
./venv/bin/pip install --editable .
Obtaining file:///home/micah/working/tor/carml
Collecting humanize (from carml==17.4.0)
Collecting ansicolors (from carml==17.4.0)
  Using cached ansicolors-1.1.8-py2.py3-none-any.whl
Collecting backports.lzma (from carml==17.4.0)
Collecting txtorcon>=0.19.1 (from carml==17.4.0)
  Using cached txtorcon-0.19.3-py2.py3-none-any.whl
Collecting txsocksx>=1.15.0.2 (from carml==17.4.0)
  Using cached txsocksx-1.15.0.2-py2-none-any.whl
Collecting click>=6.7 (from carml==17.4.0)
  Using cached click-6.7-py2.py3-none-any.whl
Collecting ipaddress>=1.0.16 (from txtorcon>=0.19.1->carml==17.4.0)
  Using cached ipaddress-1.0.18-py2-none-any.whl
Collecting zope.interface>=3.6.1 (from txtorcon>=0.19.1->carml==17.4.0)
  Using cached zope.interface-4.4.3-cp27-cp27mu-manylinux1_x86_64.whl
Collecting automat (from txtorcon>=0.19.1->carml==17.4.0)
  Using cached Automat-0.6.0-py2.py3-none-any.whl
Collecting incremental (from txtorcon>=0.19.1->carml==17.4.0)
  Using cached incremental-17.5.0-py2.py3-none-any.whl
Collecting Twisted[tls]>=15.5.0 (from txtorcon>=0.19.1->carml==17.4.0)
Collecting Parsley>=1.2 (from txsocksx>=1.15.0.2->carml==17.4.0)
  Using cached Parsley-1.3-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./venv/lib/python2.7/site-packages (from zope.interface>=3.6.1->txtorcon>=0.19.1->carml==17.4.0)
Collecting attrs (from automat->txtorcon>=0.19.1->carml==17.4.0)
  Using cached attrs-17.2.0-py2.py3-none-any.whl
Collecting six (from automat->txtorcon>=0.19.1->carml==17.4.0)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting constantly>=15.1 (from Twisted[tls]>=15.5.0->txtorcon>=0.19.1->carml==17.4.0)
  Using cached constantly-15.1.0-py2.py3-none-any.whl
Collecting hyperlink>=17.1.1 (from Twisted[tls]>=15.5.0->txtorcon>=0.19.1->carml==17.4.0)
  Using cached hyperlink-17.3.1-py2.py3-none-any.whl
Collecting service-identity; extra == "tls" (from Twisted[tls]>=15.5.0->txtorcon>=0.19.1->carml==17.4.0)
  Using cached service_identity-17.0.0-py2.py3-none-any.whl
Collecting pyopenssl>=16.0.0; extra == "tls" (from Twisted[tls]>=15.5.0->txtorcon>=0.19.1->carml==17.4.0)
  Using cached pyOpenSSL-17.3.0-py2.py3-none-any.whl
Collecting idna!=2.3,>=0.6; extra == "tls" (from Twisted[tls]>=15.5.0->txtorcon>=0.19.1->carml==17.4.0)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting pyasn1 (from service-identity; extra == "tls"->Twisted[tls]>=15.5.0->txtorcon>=0.19.1->carml==17.4.0)
  Using cached pyasn1-0.3.7-py2.py3-none-any.whl
Collecting pyasn1-modules (from service-identity; extra == "tls"->Twisted[tls]>=15.5.0->txtorcon>=0.19.1->carml==17.4.0)
  Using cached pyasn1_modules-0.1.5-py2.py3-none-any.whl
Collecting cryptography>=1.9 (from pyopenssl>=16.0.0; extra == "tls"->Twisted[tls]>=15.5.0->txtorcon>=0.19.1->carml==17.4.0)
  Using cached cryptography-2.1.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting cffi>=1.7; platform_python_implementation != "PyPy" (from cryptography>=1.9->pyopenssl>=16.0.0; extra == "tls"->Twisted[tls]>=15.5.0->txtorcon>=0.19.1->carml==17.4.0)
  Using cached cffi-1.11.2-cp27-cp27mu-manylinux1_x86_64.whl
Collecting enum34; python_version < "3" (from cryptography>=1.9->pyopenssl>=16.0.0; extra == "tls"->Twisted[tls]>=15.5.0->txtorcon>=0.19.1->carml==17.4.0)
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography>=1.9->pyopenssl>=16.0.0; extra == "tls"->Twisted[tls]>=15.5.0->txtorcon>=0.19.1->carml==17.4.0)
  Using cached asn1crypto-0.23.0-py2.py3-none-any.whl
Collecting pycparser (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=1.9->pyopenssl>=16.0.0; extra == "tls"->Twisted[tls]>=15.5.0->txtorcon>=0.19.1->carml==17.4.0)
Installing collected packages: humanize, ansicolors, backports.lzma, ipaddress, zope.interface, attrs, six, automat, incremental, constantly, hyperlink, pycparser, cffi, enum34, idna, asn1crypto, cryptography, pyopenssl, pyasn1, pyasn1-modules, service-identity, Twisted, txtorcon, Parsley, txsocksx, click, carml
  Running setup.py develop for carml
Successfully installed Parsley-1.3 Twisted-17.9.0 ansicolors-1.1.8 asn1crypto-0.23.0 attrs-17.2.0 automat-0.6.0 backports.lzma-0.0.8 carml cffi-1.11.2 click-6.7 constantly-15.1.0 cryptography-2.1.1 enum34-1.1.6 humanize-0.5.1 hyperlink-17.3.1 idna-2.6 incremental-17.5.0 ipaddress-1.0.18 pyasn1-0.3.7 pyasn1-modules-0.1.5 pycparser-2.18 pyopenssl-17.3.0 service-identity-17.0.0 six-1.11.0 txsocksx-1.15.0.2 txtorcon-0.19.3 zope.interface-4.4.3
micah@reeds:carml$ torsocks ssh -v hmsjlqkrq7mfnkpr.onion^C
micah@reeds:carml130$ bin/car^C
micah@reeds:carml130$ . venv/
bin/     include/ lib/     local/   share/   
micah@reeds:carml130$ . venv/bin/activate
(venv) micah@reeds:carml$ carm^C
(venv) micah@reeds:carml130$ carml relay --info DebianTorNode
Traceback (most recent call last):
  File "/home/micah/working/tor/carml/venv/bin/carml", line 11, in <module>
    load_entry_point('carml', 'console_scripts', 'carml')()
  File "/home/micah/working/tor/carml/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/micah/working/tor/carml/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/home/micah/working/tor/carml/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/home/micah/working/tor/carml/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/micah/working/tor/carml/carml/__init__.py", line 6, in <module>
    from carml.dispatch import dispatch
ImportError: No module named dispatch
(venv) micah@reeds:carml1$ 
```

**Comment by meejah** [comment]
Hoping this is gone? If not in the latest release, please re-open
