### ISSUE TITLE
Selecting by fingerprint not working

### ISSUE THREAD

**Issue by meejah** [meejah/carml#60]
@meejah 

carml could allow relay fingerprints to be specified:

```
$ /home/user/.local/bin/carml --connect tcp:127.0.0.1:8002 -d -p pbCKWPlvh2Zw2MDUYaTvWPTl circ -b 26ECEB6CB8B7C31031A4E220B1E2B82935032B10,A0B5B5906EB13F213D7CA9AFEC91934BE3A5930F,CA1684516B7FECF3DB76D43FD02F56D8B95E8A69
Couldn't look up 26ECEB6CB8B7C31031A4E220B1E2B82935032B10, but it looks like an ID
Error: 'str' object has no attribute 'name_is_unique'
Traceback (most recent call last):
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/twisted/internet/defer.py", line 874, in callback
    self._startRunCallbacks(result)
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/twisted/internet/defer.py", line 981, in _startRunCallbacks
    self._runCallbacks()
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/twisted/internet/defer.py", line 1075, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/twisted/internet/defer.py", line 1946, in _gotResultInlineCallbacks
    _inlineCallbacks(r, gen, status, context)
--- <exception caught here> ---
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/twisted/internet/defer.py", line 2000, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/carml/cli.py", line 200, in _startup
    await cmd(reactor, cfg, tor, *args, **kwargs)
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/carml/carml_circ.py", line 158, in run
    await build_circuit(reactor, cfg, tor, build.split(','))
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/carml/carml_circ.py", line 126, in build_circuit
    print("Building circuit:", '->'.join(util.nice_router_name(r) for r in routers))
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/carml/carml_circ.py", line 126, in <genexpr>
    print("Building circuit:", '->'.join(util.nice_router_name(r) for r in routers))
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/carml/util.py", line 120, in nice_router_name
    if router.name_is_unique:
builtins.AttributeError: 'str' object has no attribute 'name_is_unique'

```

Many Tor relays has "Unnamed" as names and some other has repeated names. Allowing selection of relays by fingerprint would be a nice thing to have in carml.

_Originally posted by @przemyslaw0 in https://github.com/meejah/carml/issues/58#issuecomment-1819392182_

**Comment by meejah** [comment]
released 23.11.1

**Comment by przemyslaw0** [comment]
I made a test with the new version using some relay fingerprints I got from https://nusenu.github.io/OrNetStats/w/

I hope they are online

Still doesn't work:

```
$ /home/user/.local/bin/carml --connect tcp:127.0.0.1:7002 -d -p blah circ -b 26ECEB6CB8B7C31031A4E220B1E2B82935032B10,2322F9A66D456AD9C880D14ECEA83960D36541D4,CA1684516B7FECF3DB76D43FD02F56D8B95E8A69
Error: Couldn't look up 26ECEB6CB8B7C31031A4E220B1E2B82935032B10 (but it looks like an ID)
Traceback (most recent call last):
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/twisted/internet/defer.py", line 874, in callback
    self._startRunCallbacks(result)
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/twisted/internet/defer.py", line 981, in _startRunCallbacks
    self._runCallbacks()
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/twisted/internet/defer.py", line 1075, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/twisted/internet/defer.py", line 1946, in _gotResultInlineCallbacks
    _inlineCallbacks(r, gen, status, context)
--- <exception caught here> ---
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/twisted/internet/defer.py", line 2000, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/carml/cli.py", line 200, in _startup
    await cmd(reactor, cfg, tor, *args, **kwargs)
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/carml/carml_circ.py", line 157, in run
    await build_circuit(reactor, cfg, tor, build.split(','))
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/carml/carml_circ.py", line 121, in build_circuit
    routers = [
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/carml/carml_circ.py", line 122, in <listcomp>
    find_router(i, r)
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/carml/carml_circ.py", line 117, in find_router
    raise RuntimeError("Couldn't look up %s (but it looks like an ID)" % name)
builtins.RuntimeError: Couldn't look up 26ECEB6CB8B7C31031A4E220B1E2B82935032B10 (but it looks like an ID)

```

**Comment by meejah** [comment]
try "`carml relay --list`" to see which relays are currently in the consensus.

**Comment by przemyslaw0** [comment]
OK, these fingerprints are on the consensus given  `"carml relay --list"`

```
$ /home/user/.local/bin/carml --connect tcp:127.0.0.1:7002 -d -p blah circ -b 299CC5D7A58E5B92B69DC333B28D926CD7B157D8,60C24AFF465D2E7FB6E9375E243F894E2939DF27,9661AC95717798884F3E3727D360DD98D66727CC
Building circuit: ~carlos1001->~Unnamed->~erdapfel
Circuit ID 15: carlos1001 -> Unnamed -> erdapfelError: failed (TIMEOUT, ).
Traceback (most recent call last):
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/twisted/internet/defer.py", line 913, in errback
    self._startRunCallbacks(fail)
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/twisted/internet/defer.py", line 981, in _startRunCallbacks
    self._runCallbacks()
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/twisted/internet/defer.py", line 1075, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/twisted/internet/defer.py", line 1946, in _gotResultInlineCallbacks
    _inlineCallbacks(r, gen, status, context)
--- <exception caught here> ---
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/twisted/internet/defer.py", line 1996, in _inlineCallbacks
    result = context.run(
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/twisted/python/failure.py", line 519, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/carml/cli.py", line 200, in _startup
    await cmd(reactor, cfg, tor, *args, **kwargs)
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/carml/carml_circ.py", line 157, in run
    await build_circuit(reactor, cfg, tor, build.split(','))
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/carml/carml_circ.py", line 140, in build_circuit
    await all_done
builtins.RuntimeError: failed (TIMEOUT, ).

 -> carlos1001 -> Unnamed -> erdapfel: built.
: closed.
```

The torrc used:

```
SocksPort 127.0.0.1:7001
ControlPort 127.0.0.1:7002
User user
NewCircuitPeriod 28800
MaxCircuitDirtiness 28800
EnforceDistinctSubnets 0
ClientUseIPv4 1
ClientUseIPv6 1
GeoIPFile /usr/share/tor/geoip
GeoIPv6File /usr/share/tor/geoip6
ClientOnly 1
ConnectionPadding 1
CookieAuthentication 1
CookieAuthFileGroupReadable 1
HashedControlPassword 16:49F40A2AE44A1AAE60CB0804AA096B2EAB0B70B30FA75E01D89078265E
DataDirectory /home/user/Temp/carml
HTTPSProxy 127.0.0.1:3129
```

**Comment by meejah** [comment]
That's a different error (and looks .. possible-legitimate? It seems like it extended to the exit but then something timed out?)

**Comment by przemyslaw0** [comment]
"carml relay --list" doesn't print the information that distinguish if a relay fingerprint belongs to a exit node or a entry/middle relay.

Can a Tor exit node flagged as "exit" be used as a middle/entry node?

**Comment by meejah** [comment]
Not as an entry. I _think_ so as a middle.

**Comment by meejah** [comment]
Also, "controller constructed" circuits cannot be used for Onion services (even if they go to one of the correct Introduction Points).

**Comment by przemyslaw0** [comment]
New test, now it works:

```
$ /home/user/.local/bin/carml --connect tcp:127.0.0.1:7002 -d -p blah circ -b 06C397676A6407BDE1C8836FC49CD42F38B8082E,0FD14DA848774DC90FED459A723804CC16C44970,5628495D9939A8C139DD441402DE42F7012B7092
Building circuit: ~Whitetree->~MSchnelltra->~relayondiinkarazan
Circuit ID 28: Whitetree -> MSchnelltra -> relayondiinkarazan: built.

$ /home/user/.local/bin/carml --connect tcp:127.0.0.1:7002 -d -p blah circ -b 00DA4A3852EA5EF6841B8B4372DB0EFD3AB0BE92,0FD14DA848774DC90FED459A723804CC16C44970,5BE1A8D8A7D16E9FA2EF3B97D3C9A86D8498A407
Building circuit: ~ChumBucket->~MSchnelltra->~Doughboy
Circuit ID 31: ChumBucket -> MSchnelltra -> Doughboy: built.
```

I realized that nodes should be carefully selected, nodes with 100% chance of working with carml are ones marked as "stable": https://metrics.torproject.org/rs.html#search/flag:stable%20

For exit, I can see that some relays fails some times, but it is not a problem.

Thanks @meejah for the fix, now I know the trick.
