### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'tcp'

### ISSUE THREAD

**Issue by MeisterP** [meejah/carml#9]
If `TOR_CONTROL_PORT` is set, carml fails with `ValueError: invalid literal for int() with base 10: 'tcp'`

```
TOR_CONTROL_PORT=9051 carml circ --list
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/carml", line 11, in <module>
    load_entry_point('carml==17.2.0', 'console_scripts', 'carml')()
  File "/usr/lib64/python2.7/site-packages/carml/dispatch.py", line 196, in dispatch
    endpoint = endpoints.clientFromString(reactor, 'tcp:' + options['connect'])
  File "/usr/lib64/python2.7/site-packages/twisted/internet/endpoints.py", line 1760, in clientFromString
    kwargs = _clientParsers[name](*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/twisted/internet/endpoints.py", line 1537, in _parseClientTCP
    kwargs['port'] = int(args[0])
ValueError: invalid literal for int() with base 10: 'tcp'
```

**Comment by meejah** [comment]
Thanks for the report! Should be fixed now (on master)
